default: &default
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_user_name: <%= ENV['SMTP_USER_NAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_ssl: <%= ENV['SMTP_SSL'] %>
  default_url: <%= ENV['DEFAULT_URL'] %>
  recaptcha_secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
  recaptcha_site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>

development:
  <<: *default

test:
  <<: *default

preview:
  <<: *default

production:
  <<: *default
